### ISSUE TITLE
If I wanted to add a legend to the custom Gantt chart, how would I go about it?

### ISSUE THREAD

**Issue by giorgiopagnoni** [apache/echarts-examples#15]
[Link to chart](https://echarts.apache.org/examples/en/editor.html?c=custom-gantt-flight)
For example, a legend with the two colors that make up the rectangles? Thank you.

**Comment by Ovilia** [comment]
Please refer to [this example](https://echarts.apache.org/examples/en/editor.html?c=cycle-plot).
