### ISSUE TITLE
Animations in "Gauge Car" lag in Firefox 73 on OSX Mojave

### ISSUE THREAD

**Issue by giorgiopagnoni** [apache/echarts-examples#16]
I don't know if the same happens on other OS. It doesn't happen in Chrome.
The other two examples are fine (Gauge & Gauge Car Dark).
I don't know if there's something wrong with the example or if it's a problem within the library.

**Comment by plainheart** [comment]
If it doesn't appear in other browsers except for Firefox, it should be not a problem within ECharts.
