### ISSUE TITLE
eChart GL examples don't work anymore

### ISSUE THREAD

**Issue by dominic-simplan** [apache/echarts-examples#19]
At least some of the eChart GL examples seem to be not working anymore, for example the [airlines on globe](https://echarts.apache.org/examples/en/editor.html?c=lines3d-airline-on-globe&gl=1) throws an error in the console (Chrome, Firefox, IE11): 

> Uncaught DOMException: Failed to execute 'texImage2D' on 'WebGLRenderingContext': The image element contains cross-origin data, and may not be loaded.

I believe it was working correctly a few days ago.

**Comment by plainheart** [comment]
I don't know what happened that time but it works currently.
