### ISSUE TITLE
How to fetch data from api in any of the example ?

### ISSUE THREAD

**Issue by aditya-manit** [apache/echarts-examples#38]
I am trying to fetch data to built  a chart from an API, but I cannot add any imports to chart files (eg: `area-simple.js`)

On adding `import axios from 'axios';`
Its giving me error: `SyntaxError: Cannot use import statement outside a module`

I have tried using require but then I am getting:
On adding `const axios = require('axios');`
It giving me error: `ReferenceError: require is not defined`

I am kinda new to webpack, Can someone please guide me to the correct way to call an api and use its data in `area-simple.js` file or any other file.

**Comment by plainheart** [comment]
I don't know if you have solved this problem. For simplicity, it's suggested to use the native [`fetch`](https://developer.mozilla.org/en-US/docs/Web/API/fetch), which needs no third-party library.
