### ISSUE TITLE
Cannot run example on local

### ISSUE THREAD

**Issue by Gumichocopengin8** [apache/echarts-examples#69]
When I followed the README instruction, I got some errors and couldn't run.
`npm install` produces these errors

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: @lang/object-visualizer@4.2.0
npm ERR! Found: vue@2.6.14
npm ERR! node_modules/vue
npm ERR!   dev vue@"2.6.14" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer vue@"^3.0.2" from @lang/object-visualizer@4.2.0
npm ERR! node_modules/@lang/object-visualizer
npm ERR!   @lang/object-visualizer@"^4.2.0" from the root project
``` 

but `nom install --force` worked. 

after that, I ran `nom run dev`, but it didnt load the page at all. 
How can I run this repo on local?
Thanks

### Env

- node v18.10.0
- npm 9.5.1

**Comment by tyn1998** [comment]
Hi @Gumichocopengin8, I have run this project months ago. I think a lower version such as Node v14 should be set in your machine and you'd better follow the steps described in the [README](https://github.com/apache/echarts-examples/tree/dev) of `dev` branch.

**Comment by Gumichocopengin8** [comment]
Thank you. it works with node v16
also, need to change `localhost` instead of `127.0.0.1`
