### ISSUE TITLE
Latest update defaults to chinese

### ISSUE THREAD

**Issue by caesarshift** [apache/echarts-examples#7]
With the latest changes, the default URL listed in the readme goes to the chinese version of the site. Can we update the readme with both URLs?

Default (Chinese): https://ecomfe.github.io/echarts-examples/public
English: https://ecomfe.github.io/echarts-examples/public/en/
Chinese: https://ecomfe.github.io/echarts-examples/public/zh/

Additionally, the english version of the site (https://ecomfe.github.io/echarts-examples/public/en/) needs an updated menu link for "Examples" When you choose "Examples", you get the Default (Chinese) URL. It should be to the English version of examples (https://ecomfe.github.io/echarts-examples/public/en/index.html)

**Comment by Ovilia** [comment]
https://ecomfe.github.io/echarts-examples was currently under construction. Please visit https://echarts.apache.org/examples/en/index.html instead. 
https://ecomfe.github.io/echarts-examples will be redirected to apache domain. Thanks!
