### ISSUE TITLE
Unable to add a new chart on local

### ISSUE THREAD

**Issue by Gumichocopengin8** [apache/echarts-examples#70]
I tried to add a new chart in the examples. 

### Steps I tried

1. added a file in `public/examples/ts/new-chart.ts`
2. added a chart data into `src/data/chart-list-data.js`
3. ran `npm run dev`
4. open `http://localhost:3002/en/index.html`
5. found the chart component I made
6. clicked the component
7. just saw blank editor and preview page

How can I show the code and preview on local? 

---

I also read [the doc](https://github.com/apache/echarts-examples#use-local-echarts-build). 
> Update the URL of localEChartsDir & localEChartsGLJS in src/common/config.js

This part is a bit confusing. How should I update the URL of them? 

> Add local=1 in URL

Do I need to run some commands to generate code and/or preview for local?

**Comment by tyn1998** [comment]
`npm run compile:example` should be run first. 

Please see: https://github.com/apache/echarts-examples/tree/dev#how

**Comment by tyn1998** [comment]
> This part is a bit confusing. How should I update the URL of them?

If your new chart depends on a local version of ECharts(which often means it is a developing version of your own), then you must do the two things as instructed to make sure the website loads the ECharts from local rather outside:

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/32434520/221805800-8b5a7561-0699-4a66-949e-fe00007fd129.png">

<img width="1472" alt="image" src="https://user-images.githubusercontent.com/32434520/221805875-6bffbeac-5a71-4518-91ca-ed6f5abf9466.png">

You should also run a web server like `http-server` to serve the local ECharts.

**Comment by Gumichocopengin8** [comment]
Thank you for the detailed instruction. I could successfully display the chart. 
Also, I needed to run `rpm run build:example` to generate the image and preview
