### ISSUE TITLE
All example thumb images and chart javascript files are broken

### ISSUE THREAD

**Issue by wolfg1969** [apache/echarts-examples#8]
![Screen Shot 2019-06-05 at 11 04 02](https://user-images.githubusercontent.com/1585718/58927582-c197e900-8781-11e9-8b85-2ce7b2f37762.png)

![Screen Shot 2019-06-05 at 11 04 34](https://user-images.githubusercontent.com/1585718/58927584-c197e900-8781-11e9-9e9f-b7af508b7bc9.png)

**Comment by Ovilia** [comment]
I think this has been fixed. If not, please provide the URL.

**Comment by wolfg1969** [comment]
Yes. Thanks.
