### ISSUE TITLE
第一步我就卡住了，请求答疑

### ISSUE THREAD

**Issue by newpost** [apache/echarts-examples#87]
E:\github\echarts-examples>npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: @lang/object-visualizer@4.2.0
npm ERR! Found: vue@2.6.14
npm ERR! node_modules/vue
npm ERR!   dev vue@"2.6.14" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer vue@"^3.0.2" from @lang/object-visualizer@4.2.0
npm ERR! node_modules/@lang/object-visualizer
npm ERR!   @lang/object-visualizer@"^4.2.0" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: vue@3.3.10
npm ERR! node_modules/vue
npm ERR!   peer vue@"^3.0.2" from @lang/object-visualizer@4.2.0
npm ERR!   node_modules/@lang/object-visualizer
npm ERR!     @lang/object-visualizer@"^4.2.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR!
npm ERR! For a full report see

**Comment by otakustay** [comment]
用`npm install --legacy-peer-deps`

**Comment by plainheart** [comment]
强制安装下即可。
