### ISSUE TITLE
can i indication number points appear in xAxis in bar large data??

### ISSUE THREAD

**Issue by cuongdevjs** [apache/echarts-examples#9]
Link example [https://echarts.apache.org/examples/en/editor.html?c=bar-large](url)

**Comment by Ovilia** [comment]
Sorry. What do you want?

**Comment by cuongdevjs** [comment]
`
var dataCount = 1440;
var data = generateData(dataCount);

var option = {
    title: {
        text: echarts.format.addCommas(dataCount) + ' Data',
        left: 10
    },
    toolbox: {
        feature: {
            dataZoom: {
                yAxisIndex: false
            },
            saveAsImage: {
                pixelRatio: 2
            }
        }
    },
    tooltip: {
        trigger: 'axis',
        axisPointer: {
            type: 'shadow'
        }
    },
    grid: {
        bottom: 90
    },
    dataZoom: [],
    xAxis: {
        // type: category,
        data: data.categoryData,
        axisLabel: {
            formatter: function (value, idx) {
              var date = new Date(value);
              return idx === 0 ?
              '00:00' + [date.getDate(), date.getMonth() + 1, date.getFullYear()].join('/')
              : [date.getHours(), date.getMinutes() < 10 ? `0${date.getMinutes()}` : date.getMinutes()].join(':');
            }
          },
        silent: true,
        boundaryGap: false
    },
    yAxis: {
        splitArea: {
            show: false
        }
    },
    series: [{
        type: 'line',
        data: data.valueData,
        // Set `large` for large data amount
        large: true
    }]
};

function generateData(count) {
    var baseValue = Math.random() * 1000;
    var time = +new Date(2011, 0, 1);
    var smallBaseValue;

    function next(idx) {
        smallBaseValue = idx % 30 === 0
            ? Math.random() * 700
            : (smallBaseValue + Math.random() * 500 - 250);
        baseValue += Math.random() * 20 - 10;
        return Math.max(
            0,
            Math.round(baseValue + smallBaseValue) + 3000
        );
    }

    var categoryData = [];
    var valueData = [];

    for (var i = 0; i < count; i++) {
        categoryData.push(echarts.format.formatTime('yyyy-MM-dd\nhh:mm:ss', time));
        valueData.push(next(i).toFixed(2));
        time += 60000;
    }

    return {
        categoryData: categoryData,
        valueData: valueData
    };
}
`

I want to display the value in xAxis is: 00:00AM, 01:00AM, ...etc. please help me

**Comment by Ovilia** [comment]
Yes, it's set in `xAxis. axisLabel.formatter`. The rest is pure js. Please be patient and if you still have problem, you can ask on http://stackoverflow.com . I'm closing this issue because it's not ECharts example related.

**Comment by cuongdevjs** [comment]
no, but i can't indicate point number display in xaxis, example i just want display 24 point compatible time hours in day in x axis? I can't find solution, pls help me

**Comment by Ovilia** [comment]
Use Chrome Inspect to debug.
