### ISSUE TITLE
主题theme 

### ISSUE THREAD

**Issue by utah2016** [apache/echarts-examples#94]
求问怎样更改examples的主题，直接注册的主题文件没有生效

**Comment by plainheart** [comment]
想在[编辑器](https://echarts.apache.org/examples/editor.html)里修改主题吗？

**Comment by utah2016** [comment]
> 想在[编辑器](https://echarts.apache.org/examples/editor.html)里修改主题吗？



> 想在[编辑器](https://echarts.apache.org/examples/editor.html)里修改主题吗？

不是的，是修改这个examples项目的主题

**Comment by utah2016** [comment]
> 想在[编辑器](https://echarts.apache.org/examples/editor.html)里修改主题吗？

已经在主题构建工具导出了主题文件，想配置到echarts-examples项目中预览下效果

**Comment by plainheart** [comment]
如果是 clone 这个项目修改的话，可以在[这行](https://github.com/apache/echarts-examples/blob/gh-pages/src/editor/sandbox/srcdoc.html#L67)后面引入一下你的主题文件，然后 URL 参数加上 theme=主题名称，例如：https://echarts.apache.org/examples/zh/editor.html?c=pie-simple&theme=vintage

**Comment by utah2016** [comment]
> 如果是 clone 这个项目修改的话，可以在[这行](https://github.com/apache/echarts-examples/blob/gh-pages/src/editor/sandbox/srcdoc.html#L67)后面引入一下你的主题文件，然后 URL 参数加上 theme=主题名称，例如：https://echarts.apache.org/examples/zh/editor.html?c=pie-simple&theme=vintage

按照咱们指示加入自定义主题js文件，但是在加载资源会加载咱们官方配置的cdn资源，是不是还有别的地方需要修改
![echarts9](https://github.com/apache/echarts-examples/assets/22965852/cf1e05ba-9d6b-4da9-9e9a-14f98d3a59f9)

**Comment by utah2016** [comment]
> 如果是 clone 这个项目修改的话，可以在[这行](https://github.com/apache/echarts-examples/blob/gh-pages/src/editor/sandbox/srcdoc.html#L67)后面引入一下你的主题文件，然后 URL 参数加上 theme=主题名称，例如：https://echarts.apache.org/examples/zh/editor.html?c=pie-simple&theme=vintage

好的，谢谢

**Comment by plainheart** [comment]
那个报错应该可以忽略，因为你引入的主题文件会覆盖前者。没问题的话记得关闭 issue 哈。

**Comment by utah2016** [comment]
> 那个报错应该可以忽略，因为你引入的主题文件会覆盖前者。没问题的话记得关闭 issue 哈。

好的
